events {
        # Events directives....
}

http {

     server {
    listen 80;
    server_name week-25-prod-http.ayushraj.site;

    location / {
        proxy_pass http://localhost:3000; # Forwards to backend server
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
            server {
    listen 80;
    server_name week-25-prod-http-ws.ayushraj.site;

    location / {
        proxy_pass http://localhost:3001; # Forwards to backend server
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    server {
    listen 80;
    server_name week-25-prod-fe.ayushraj.site;

    location / {
        proxy_pass http://localhost:3002; # Forwards to backend server
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

}
}

            