// This file was generated by Prisma, and assumes you run Prisma commands using `pnpm prisma [command]` or `npx prisma [command]`.
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_e0TcChzm9IKs@ep-proud-queen-adqmusf6-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
  },
});
