name: Deploy to development

on:
  push:
    branches:
     - "main"

  jobs:
    redeploy_everything:
    run-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run : | 
          "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{secrets.KNOWN_HOST}}" &> ~/home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh i ~/ssh_key root@44.201.56.84 -t "cd devops-basic/ && git pull origin main && pnpm install && pnpm run build && pm2 restart web && pm2 restart http-server && pm2 restart ws-server"